apiVersion: extensions/v1beta1
kind: DaemonSet                     
metadata:
  name: kube-policy-manager
  labels:
    app: kube-policy-manager
spec:
  template:
    metadata:
      labels:
        name: kube-policy-manager
    spec:
      hostNetwork: true
      containers:
      - name: kube-policy-manager
        image: chiradeep/kube-policy-manager:0.22
        args: ["--logtostderr=1", "--v=4"]
        securityContext:
         privileged: true
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

